config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get 'signup', to: 'registrations#new'
  post 'signup', to: 'registrations#create'
  get 'signout', to: 'authentication#destroy'
  get 'signin', to: 'authentication#new'
  post 'signin', to: 'authentication#create'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :email, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if session[:user_id].present?
      User.find(session[:user_id])
    end
  end

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Thanks for signing in"
      redirect_to root_path
    else
      flash[:notice] = "Oops, something went wrong"
      render :new
    end
  end


  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:email, :password))
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thanks for signing up"
      redirect_to "/"
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
<%= form_tag signin_path do %>
  <%= label_tag :email %>
  <%= text_field_tag :email %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <%= submit_tag "Sign In" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserAuth1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
    Current user is <%= current_user.email %> | <%= link_to "Sign out", signout_path %>
  <% else %>
    <%= link_to "Sign in", signin_path %> | <%= link_to "Sign up", signup_path %>
  <% end %>


<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1>Welcome!</h1>